<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Korisnik extends \Entity\Korisnik implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function getLozinka()
    {
        $this->__load();
        return parent::getLozinka();
    }

    public function getIme()
    {
        $this->__load();
        return parent::getIme();
    }

    public function getPrezime()
    {
        $this->__load();
        return parent::getPrezime();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getUlica()
    {
        $this->__load();
        return parent::getUlica();
    }

    public function getBroj()
    {
        $this->__load();
        return parent::getBroj();
    }

    public function getGrad()
    {
        $this->__load();
        return parent::getGrad();
    }

    public function getTelefon()
    {
        $this->__load();
        return parent::getTelefon();
    }

    public function getUloga()
    {
        $this->__load();
        return parent::getUloga();
    }

    public function getClanci()
    {
        $this->__load();
        return parent::getClanci();
    }

    public function getOblasti()
    {
        $this->__load();
        return parent::getOblasti();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function setLozinka($lozinka)
    {
        $this->__load();
        return parent::setLozinka($lozinka);
    }

    public function setIme($ime)
    {
        $this->__load();
        return parent::setIme($ime);
    }

    public function setPrezime($prezime)
    {
        $this->__load();
        return parent::setPrezime($prezime);
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setUlica($ulica)
    {
        $this->__load();
        return parent::setUlica($ulica);
    }

    public function setBroj($broj)
    {
        $this->__load();
        return parent::setBroj($broj);
    }

    public function setGrad($grad)
    {
        $this->__load();
        return parent::setGrad($grad);
    }

    public function setTelefon($telefon)
    {
        $this->__load();
        return parent::setTelefon($telefon);
    }

    public function setUloga($uloga)
    {
        $this->__load();
        return parent::setUloga($uloga);
    }

    public function korisnikovaOblast($oblast)
    {
        $this->__load();
        return parent::korisnikovaOblast($oblast);
    }

    public function checkIfUrednik($oblast)
    {
        $this->__load();
        return parent::checkIfUrednik($oblast);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'lozinka', 'ime', 'prezime', 'email', 'ulica', 'broj', 'grad', 'telefon', 'uloga', 'clanci', 'oblasti');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}